'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { Empty, Status } from '@/components/ui';
import { api } from '@/lib/api';
import { useSession } from '@/lib/store';

interface Template { id: string; name: string; content: string; variables: string[]; status: string; version: number }
export default function TemplatesPage() { const workspaceId = useSession((state) => state.workspaceId); const client = useQueryClient(); const [name, setName] = useState(''); const [content, setContent] = useState(''); const query = useQuery({ queryKey: ['templates', workspaceId], queryFn: () => api<Template[]>(`/workspaces/${workspaceId}/templates`), enabled: Boolean(workspaceId) }); const create = useMutation({ mutationFn: () => api(`/workspaces/${workspaceId}/templates`, { method: 'POST', body: JSON.stringify({ name, content, variables: [...content.matchAll(/{{\s*([\w.]+)\s*}}/g)].map((match) => match[1]) }) }), onSuccess: async () => { setName(''); setContent(''); await client.invalidateQueries({ queryKey: ['templates', workspaceId] }); } }); return <AppShell title="Mẫu tin nhắn" subtitle="Template có version, biến được phát hiện tự động và dùng lại an toàn trong campaign."><form className="panel mb-5 grid gap-3 p-5 md:grid-cols-[260px_1fr_auto]" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><input className="input" required placeholder="Tên template" value={name} onChange={(event) => setName(event.target.value)} /><input className="input" required placeholder="Xin chào {{firstName}}..." value={content} onChange={(event) => setContent(event.target.value)} /><button className="button-primary">Tạo template</button></form>{query.data?.length ? <div className="grid gap-4 md:grid-cols-2">{query.data.map((item) => <div className="panel p-5" key={item.id}><div className="flex justify-between"><h3 className="font-semibold">{item.name} <span className="text-xs text-[var(--muted)]">v{item.version}</span></h3><Status tone={item.status === 'ACTIVE' ? 'success' : 'neutral'}>{item.status}</Status></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{item.content}</p></div>)}</div> : <Empty title="Chưa có template" description="Tạo template đầu tiên để dùng trong chiến dịch consent-aware." />}</AppShell>; }
