const ok = { description: 'Successful response.' };
const accepted = { description: 'Accepted for asynchronous processing.' };
const errorResponses = {
  400: { description: 'Validation or business-rule error.' },
  401: { description: 'Authentication required.' },
  403: { description: 'Insufficient workspace permission.' },
  404: { description: 'Resource not found in this workspace.' },
  429: { description: 'Rate limit exceeded.' },
};
const bearer = [{ bearerAuth: [] }];
const workspaceParameter = {
  name: 'workspaceId',
  in: 'path',
  required: true,
  schema: { type: 'string', format: 'uuid' },
};

export const openApiDocument = {
  openapi: '3.1.0',
  info: {
    title: 'ZaloHub SaaS API',
    version: '1.0.0',
    description: 'Multi-tenant, consent-aware Zalo operations API. Platform actions use official APIs only.',
  },
  servers: [{ url: '/api/v1' }],
  tags: ['auth', 'admin', 'workspaces', 'subscriptions', 'accounts', 'contacts', 'messages', 'campaigns', 'platforms', 'audit', 'health'].map((name) => ({ name })),
  components: {
    securitySchemes: {
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
    },
    schemas: {
      RegisterRequest: {
        type: 'object',
        required: ['email', 'password', 'displayName', 'workspaceName'],
        properties: {
          email: { type: 'string', format: 'email' },
          password: { type: 'string', minLength: 12, format: 'password' },
          displayName: { type: 'string', minLength: 2, maxLength: 100 },
          workspaceName: { type: 'string', minLength: 2, maxLength: 100 },
        },
      },
      LoginRequest: {
        type: 'object',
        required: ['email', 'password'],
        properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' }, sessionName: { type: 'string' } },
      },
      TokenPair: {
        type: 'object',
        properties: { accessToken: { type: 'string' }, refreshToken: { type: 'string' }, expiresInSeconds: { type: 'integer' } },
      },
      ErrorEnvelope: {
        type: 'object',
        required: ['success', 'error'],
        properties: { success: { const: false }, error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' }, requestId: { type: 'string' } } } },
      },
    },
  },
  paths: {
    '/admin/dashboard': { get: { tags: ['admin'], summary: 'Get cross-tenant SaaS health and usage dashboard', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/tenants': { get: { tags: ['admin'], summary: 'List tenants with owner, plan and usage counts', security: bearer, responses: { 200: ok, ...errorResponses } }, post: { tags: ['admin'], summary: 'Provision tenant, owner and subscription atomically', security: bearer, responses: { 201: ok, ...errorResponses } } },
    '/admin/plans': { get: { tags: ['admin'], summary: 'List SaaS plans and entitlements', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/subscriptions': { get: { tags: ['admin'], summary: 'List tenant subscriptions', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/usage': { get: { tags: ['admin'], summary: 'Read quota usage for all tenants', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/tenants/{tenantId}/quota': { patch: { tags: ['admin'], summary: 'Override tenant quotas and feature entitlements', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/queue': { get: { tags: ['admin'], summary: 'Inspect outbound queues and paused state', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/accounts': { get: { tags: ['admin'], summary: 'List connected platform accounts across tenants', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/accounts/{accountId}/pause': { post: { tags: ['admin'], summary: 'Pause a platform account and its campaigns', security: bearer, responses: { 201: ok, ...errorResponses } }, delete: { tags: ['admin'], summary: 'Resume an administratively paused account', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/admin/emergency-stop': { post: { tags: ['admin'], summary: 'Pause all outbound queues and campaigns', security: bearer, responses: { 201: accepted, ...errorResponses } }, delete: { tags: ['admin'], summary: 'Resume outbound queues', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/auth/register': { post: { tags: ['auth'], summary: 'Register user and first workspace', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/RegisterRequest' } } } }, responses: { 201: ok, ...errorResponses } } },
    '/auth/login': { post: { tags: ['auth'], summary: 'Login', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoginRequest' } } } }, responses: { 201: ok, ...errorResponses } } },
    '/auth/refresh': { post: { tags: ['auth'], summary: 'Rotate refresh token', responses: { 201: ok, ...errorResponses } } },
    '/auth/logout': { post: { tags: ['auth'], summary: 'Revoke current refresh session', security: bearer, responses: { 201: ok, ...errorResponses } } },
    '/auth/logout-all': { post: { tags: ['auth'], summary: 'Revoke all refresh sessions', security: bearer, responses: { 201: ok, ...errorResponses } } },
    '/auth/sessions': { get: { tags: ['auth'], summary: 'List active sessions', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/auth/me': { get: { tags: ['auth'], summary: 'Get current user', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/auth/forgot-password': { post: { tags: ['auth'], summary: 'Request password reset', responses: { 201: accepted, ...errorResponses } } },
    '/auth/reset-password': { post: { tags: ['auth'], summary: 'Reset password', responses: { 201: ok, ...errorResponses } } },
    '/auth/email-verification/request': { post: { tags: ['auth'], summary: 'Request email verification', security: bearer, responses: { 201: accepted, ...errorResponses } } },
    '/auth/email-verification/verify': { post: { tags: ['auth'], summary: 'Verify email token', responses: { 201: ok, ...errorResponses } } },
    '/workspaces': {
      get: { tags: ['workspaces'], summary: 'List memberships', security: bearer, responses: { 200: ok, ...errorResponses } },
      post: { tags: ['workspaces'], summary: 'Create workspace', security: bearer, responses: { 201: ok, ...errorResponses } },
    },
    '/workspaces/{workspaceId}': { get: { tags: ['workspaces'], summary: 'Workspace overview', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/dashboard': { get: { tags: ['workspaces', 'subscriptions'], summary: 'Get tenant dashboard metrics, subscription and effective quota', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/usage': { get: { tags: ['subscriptions'], summary: 'Get effective plan, subscription and quota usage', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/members': { get: { tags: ['workspaces'], summary: 'List members', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/invitations': { post: { tags: ['workspaces'], summary: 'Invite member', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/accounts': {
      get: { tags: ['accounts'], summary: 'List social accounts', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } },
      post: { tags: ['accounts'], summary: 'Create a disconnected official-API account record', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } },
    },
    '/workspaces/{workspaceId}/accounts/zalo/oauth/start': { post: { tags: ['accounts'], summary: 'Start Zalo OA OAuth v4 with one-time PKCE state', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/platforms/zalo/oauth/callback': { get: { tags: ['accounts'], summary: 'Complete Zalo OA OAuth callback and redirect to the frontend', responses: { 303: { description: 'Redirect to the accounts page with the connection result.' }, ...errorResponses } } },
    '/platforms/zalo/webhook': { post: { tags: ['accounts'], summary: 'Verify, deduplicate and queue a Zalo OA webhook event', parameters: [{ name: 'x-zevent-signature', in: 'header', required: true, schema: { type: 'string' } }], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/accounts/{accountId}/zalo/refresh': { post: { tags: ['accounts'], summary: 'Rotate Zalo OA access and refresh tokens', security: bearer, parameters: [workspaceParameter, { name: 'accountId', in: 'path', required: true, schema: { type: 'string' } }], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/accounts/{accountId}/sync': { post: { tags: ['accounts'], summary: 'Request account sync', security: bearer, parameters: [workspaceParameter, { name: 'accountId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/contacts': {
      get: { tags: ['contacts'], summary: 'Search and paginate contacts', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } },
      post: { tags: ['contacts'], summary: 'Create contact with source and consent', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } },
    },
    '/workspaces/{workspaceId}/contacts/import': { post: { tags: ['contacts'], summary: 'Validate and queue up to 5,000 consent-aware contacts', security: bearer, parameters: [workspaceParameter], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/imports/upload': { post: { tags: ['contacts'], summary: 'Upload and validate CSV, XLSX, XLS or JSON contacts with server-side staging', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/imports': { get: { tags: ['contacts'], summary: 'List import history and progress', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/imports/{importId}': { get: { tags: ['contacts'], summary: 'Get an import job and row counters', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/imports/{importId}/preview': { get: { tags: ['contacts'], summary: 'Preview normalized, invalid and duplicate rows', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/imports/{importId}/mapping': { patch: { tags: ['contacts'], summary: 'Update source-column mapping and revalidate staged rows', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/imports/{importId}/commit': { post: { tags: ['contacts'], summary: 'Queue a validated import for background processing', security: bearer, parameters: [workspaceParameter], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/segments': { get: { tags: ['contacts'], summary: 'List dynamic contact segments', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } }, post: { tags: ['contacts'], summary: 'Create a dynamic contact segment', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/segments/{segmentId}/preview': { get: { tags: ['contacts'], summary: 'Preview contacts matching a dynamic segment', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/conversations': { get: { tags: ['messages'], summary: 'List conversations', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/conversations/{conversationId}/messages': { get: { tags: ['messages'], summary: 'Get conversation history', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/messages': { post: { tags: ['messages'], summary: 'Validate and queue an outbound message', security: bearer, parameters: [workspaceParameter], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/campaigns': {
      get: { tags: ['campaigns'], summary: 'List campaigns', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } },
      post: { tags: ['campaigns'], summary: 'Create campaign and static audience', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } },
    },
    '/workspaces/{workspaceId}/campaigns/{campaignId}/approve': { post: { tags: ['campaigns'], summary: 'Approve campaign', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/campaigns/{campaignId}/schedule': { post: { tags: ['campaigns'], summary: 'Schedule approved campaign', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/campaigns/{campaignId}/launch': { post: { tags: ['campaigns'], summary: 'Launch approved campaign', security: bearer, parameters: [workspaceParameter], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/templates': { get: { tags: ['messages'], summary: 'List versioned message templates', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } }, post: { tags: ['messages'], summary: 'Create message template', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/automations': { get: { tags: ['campaigns'], summary: 'List automation workflows', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } }, post: { tags: ['campaigns'], summary: 'Create versioned automation', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/posts': { get: { tags: ['campaigns'], summary: 'List social posts', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } }, post: { tags: ['campaigns'], summary: 'Create draft social post', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/posts/{postId}/schedule': { post: { tags: ['campaigns'], summary: 'Approve and schedule post', security: bearer, parameters: [workspaceParameter], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/posts/{postId}/publish': { post: { tags: ['campaigns'], summary: 'Queue immediate official-API publish', security: bearer, parameters: [workspaceParameter], responses: { 201: accepted, ...errorResponses } } },
    '/workspaces/{workspaceId}/calendar': { get: { tags: ['campaigns'], summary: 'Get scheduled content range', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/groups': { get: { tags: ['contacts'], summary: 'List synchronized platform groups', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/proxies': { get: { tags: ['accounts'], summary: 'List proxy metadata without secrets', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } }, post: { tags: ['accounts'], summary: 'Create encrypted proxy configuration', security: bearer, parameters: [workspaceParameter], responses: { 201: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/analytics': { get: { tags: ['audit'], summary: 'Get workspace and queue analytics', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/contacts-export.csv': { get: { tags: ['contacts'], summary: 'Export authorized workspace contacts as CSV', security: bearer, parameters: [workspaceParameter], responses: { 200: { description: 'UTF-8 CSV export.' }, ...errorResponses } } },
    '/platforms/capabilities': { get: { tags: ['platforms'], summary: 'Inspect conservative official-API capability matrix', security: bearer, responses: { 200: ok, ...errorResponses } } },
    '/workspaces/{workspaceId}/audit': { get: { tags: ['audit'], summary: 'Read immutable audit events', security: bearer, parameters: [workspaceParameter], responses: { 200: ok, ...errorResponses } } },
    '/health': { get: { tags: ['health'], summary: 'Liveness probe', responses: { 200: ok } } },
    '/ready': { get: { tags: ['health'], summary: 'Database and Redis readiness probe', responses: { 200: ok, 503: { description: 'Dependency unavailable.' } } } },
  },
} as const;
