'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Filter, Plus, Trash2, UsersRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { AppShell } from '@/components/app-shell';
import { Empty, Status } from '@/components/ui';
import { api } from '@/lib/api';
import { useSession } from '@/lib/store';

type Segment = { id: string; name: string; description?: string; filter: Record<string, unknown>; estimatedSize: number; lastEvaluated?: string };
type Tag = { id: string; name: string; color: string; _count: { contacts: number } };
type Preview = { total: number; items: Array<{ id: string; displayName: string; consentStatus: string; suppressed: boolean; normalizedPhone?: string }> };
const empty = { name: '', description: '', search: '', platform: '', consentStatus: '', suppressed: '', tagId: '', source: '' };

export default function SegmentsPage() {
  const workspaceId = useSession((state) => state.workspaceId);
  const client = useQueryClient();
  const [form, setForm] = useState(empty);
  const [activeId, setActiveId] = useState<string>();
  const [error, setError] = useState('');
  const segments = useQuery({ queryKey: ['segments', workspaceId], queryFn: () => api<Segment[]>(`/workspaces/${workspaceId}/segments`), enabled: Boolean(workspaceId) });
  const tags = useQuery({ queryKey: ['tags', workspaceId], queryFn: () => api<Tag[]>(`/workspaces/${workspaceId}/tags`), enabled: Boolean(workspaceId) });
  const preview = useQuery({ queryKey: ['segment-preview', workspaceId, activeId], queryFn: () => api<Preview>(`/workspaces/${workspaceId}/segments/${activeId}/preview`), enabled: Boolean(workspaceId && activeId) });
  const create = useMutation({ mutationFn: () => api<Segment>(`/workspaces/${workspaceId}/segments`, { method: 'POST', body: JSON.stringify({ name: form.name, description: form.description || undefined, filter: Object.fromEntries(Object.entries({ search: form.search, platform: form.platform, consentStatus: form.consentStatus, suppressed: form.suppressed === '' ? undefined : form.suppressed === 'true', tagId: form.tagId, source: form.source }).filter(([, value]) => value !== '' && value !== undefined)) }) }), onSuccess: async (result) => { setForm(empty); setActiveId(result.id); setError(''); await client.invalidateQueries({ queryKey: ['segments', workspaceId] }); }, onError: (cause: Error) => setError(cause.message) });
  const remove = useMutation({ mutationFn: (id: string) => api(`/workspaces/${workspaceId}/segments/${id}`, { method: 'DELETE' }), onSuccess: async () => { setActiveId(undefined); await client.invalidateQueries({ queryKey: ['segments', workspaceId] }); }, onError: (cause: Error) => setError(cause.message) });

  return <AppShell title="Phân khúc khách hàng" subtitle="Tạo segment động theo nền tảng, consent, suppression, tag, nguồn và từ khóa.">
    {error && <div className="mb-5 rounded-xl border border-rose-400/40 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</div>}
    <form className="panel mb-5 p-5" onSubmit={(event: FormEvent) => { event.preventDefault(); create.mutate(); }}><div className="mb-4 flex items-center gap-2"><Filter size={18} className="text-teal-300" /><h2 className="font-semibold">Segment mới</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input className="input" required placeholder="Tên segment" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input className="input" placeholder="Mô tả" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><input className="input" placeholder="Tìm tên / SĐT / Zalo ID" value={form.search} onChange={(event) => setForm({ ...form, search: event.target.value })} /><input className="input" placeholder="Nguồn chứa…" value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value })} /><select className="input" value={form.platform} onChange={(event) => setForm({ ...form, platform: event.target.value })}><option value="">Mọi nền tảng</option><option value="ZALO">Zalo</option><option value="FACEBOOK">Facebook</option><option value="TIKTOK">TikTok</option></select><select className="input" value={form.consentStatus} onChange={(event) => setForm({ ...form, consentStatus: event.target.value })}><option value="">Mọi consent</option><option>OPTED_IN</option><option>UNKNOWN</option><option>OPTED_OUT</option></select><select className="input" value={form.suppressed} onChange={(event) => setForm({ ...form, suppressed: event.target.value })}><option value="">Mọi suppression</option><option value="false">Có thể liên hệ</option><option value="true">Đã suppression</option></select><select className="input" value={form.tagId} onChange={(event) => setForm({ ...form, tagId: event.target.value })}><option value="">Mọi tag</option>{tags.data?.map((tag) => <option key={tag.id} value={tag.id}>{tag.name} ({tag._count.contacts})</option>)}</select></div><button className="button-primary mt-4" disabled={create.isPending}><Plus className="mr-2 inline" size={16} />Tạo segment và tính quy mô</button></form>
    <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="panel p-4"><h2 className="mb-3 font-semibold">Danh sách segment</h2>{segments.data?.length ? <div className="space-y-2">{segments.data.map((segment) => <button className={`w-full rounded-xl border p-3 text-left ${activeId === segment.id ? 'border-teal-400/60 bg-teal-400/10' : 'border-[var(--border)]'}`} key={segment.id} onClick={() => setActiveId(segment.id)}><div className="flex items-center justify-between"><span className="font-medium">{segment.name}</span><span className="text-sm font-bold text-teal-300">{segment.estimatedSize.toLocaleString('vi-VN')}</span></div><p className="mt-1 line-clamp-2 text-xs text-[var(--muted)]">{segment.description || JSON.stringify(segment.filter)}</p></button>)}</div> : <Empty title="Chưa có segment" description="Tạo phân khúc động đầu tiên ở biểu mẫu phía trên." />}</div><div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] p-4"><div className="flex items-center gap-2"><UsersRound size={18} className="text-teal-300" /><h2 className="font-semibold">Preview tối đa 50 contact</h2></div>{activeId && <button className="button-ghost !px-3 !py-2 text-xs" onClick={() => { if (window.confirm('Xóa segment này?')) remove.mutate(activeId); }}><Trash2 className="mr-1 inline" size={14} />Xóa</button>}</div>{preview.data?.items.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Contact</th><th>Điện thoại</th><th>Consent</th></tr></thead><tbody>{preview.data.items.map((contact) => <tr key={contact.id}><td className="font-medium">{contact.displayName}</td><td>{contact.normalizedPhone ?? '—'}</td><td><Status tone={contact.suppressed ? 'danger' : contact.consentStatus === 'OPTED_IN' ? 'success' : 'warning'}>{contact.suppressed ? 'SUPPRESSED' : contact.consentStatus}</Status></td></tr>)}</tbody></table></div> : <div className="p-6"><Empty title={activeId ? 'Segment không có contact' : 'Chọn một segment'} description={activeId ? 'Hãy điều chỉnh bộ lọc để mở rộng phân khúc.' : 'Preview sẽ hiển thị contact khớp điều kiện.'} /></div>}</div></div>
  </AppShell>;
}
