'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, Download, FileUp, Search, Tag as TagIcon, UserCheck, UserPlus, UserX } from 'lucide-react';
import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { AppShell } from '@/components/app-shell';
import { Empty, Status } from '@/components/ui';
import { api, apiBlob } from '@/lib/api';
import { useSession } from '@/lib/store';

type Contact = { id: string; displayName: string; platform: string; platformUserId?: string; email?: string; normalizedPhone?: string; source?: string; consentStatus: string; suppressed: boolean; tags: Array<{ tag: Tag }> };
type Tag = { id: string; name: string; color: string; _count?: { contacts: number } };
type ContactsResponse = { items: Contact[]; pagination: { total: number; page: number; pages: number } };
type ContactForm = { platform: 'ZALO' | 'FACEBOOK' | 'TIKTOK'; platformUserId: string; displayName: string; phone: string; email: string; source: string; consentStatus: 'UNKNOWN' | 'OPTED_IN' | 'OPTED_OUT'; consentSource: string };
const empty: ContactForm = { platform: 'ZALO', platformUserId: '', displayName: '', phone: '', email: '', source: 'MANUAL', consentStatus: 'UNKNOWN', consentSource: '' };

export default function ContactsPage() {
  const workspaceId = useSession((state) => state.workspaceId);
  const client = useQueryClient();
  const [form, setForm] = useState(empty);
  const [search, setSearch] = useState('');
  const [consentFilter, setConsentFilter] = useState('');
  const [selected, setSelected] = useState<string[]>([]);
  const [tagName, setTagName] = useState('');
  const [tagId, setTagId] = useState('');
  const [message, setMessage] = useState<{ kind: 'ok' | 'error'; text: string }>();
  const params = new URLSearchParams({ limit: '100', ...(search ? { search } : {}), ...(consentFilter ? { consent: consentFilter } : {}) });
  const query = useQuery({ queryKey: ['contacts', workspaceId, search, consentFilter], queryFn: () => api<ContactsResponse>(`/workspaces/${workspaceId}/contacts?${params}`), enabled: Boolean(workspaceId) });
  const tags = useQuery({ queryKey: ['tags', workspaceId], queryFn: () => api<Tag[]>(`/workspaces/${workspaceId}/tags`), enabled: Boolean(workspaceId) });
  const refresh = async () => { setSelected([]); await Promise.all([client.invalidateQueries({ queryKey: ['contacts', workspaceId] }), client.invalidateQueries({ queryKey: ['tags', workspaceId] })]); };
  const create = useMutation({ mutationFn: () => api(`/workspaces/${workspaceId}/contacts`, { method: 'POST', body: JSON.stringify(Object.fromEntries(Object.entries(form).filter(([, value]) => value !== ''))) }), onSuccess: async () => { setForm(empty); setMessage({ kind: 'ok', text: 'Đã lưu contact và lịch sử consent.' }); await refresh(); }, onError: (error: Error) => setMessage({ kind: 'error', text: error.message }) });
  const createTag = useMutation({ mutationFn: () => api<Tag>(`/workspaces/${workspaceId}/tags`, { method: 'POST', body: JSON.stringify({ name: tagName, color: '#2dd4bf' }) }), onSuccess: async (result) => { setTagName(''); setTagId(result.id); await refresh(); }, onError: (error: Error) => setMessage({ kind: 'error', text: error.message }) });
  const bulk = useMutation({ mutationFn: (operation: 'TAG' | 'ARCHIVE' | 'SUPPRESS' | 'OPT_IN' | 'OPT_OUT') => api<{ affected: number }>(`/workspaces/${workspaceId}/contacts/bulk`, { method: 'POST', body: JSON.stringify({ contactIds: selected, operation, ...(operation === 'TAG' ? { tagId } : {}) }) }), onSuccess: async (result) => { setMessage({ kind: 'ok', text: `Đã cập nhật ${result.affected} contact.` }); await refresh(); }, onError: (error: Error) => setMessage({ kind: 'error', text: error.message }) });
  const items = query.data?.items ?? [];
  const allSelected = items.length > 0 && items.every((item) => selected.includes(item.id));
  const exportContacts = async () => { try { const blob = await apiBlob(`/workspaces/${workspaceId}/contacts-export.csv`); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'contacts.csv'; link.click(); URL.revokeObjectURL(url); } catch (error) { setMessage({ kind: 'error', text: error instanceof Error ? error.message : 'Không thể xuất danh bạ.' }); } };

  return <AppShell title="CRM & Consent" subtitle={`${query.data?.pagination.total ?? 0} contacts · Dedupe theo tenant, tag, segment, bulk action và suppression.`} action={<div className="flex gap-2"><button className="button-ghost" onClick={() => void exportContacts()}><Download className="mr-2 inline" size={16} />Xuất CSV</button><Link className="button-primary" href="/data"><FileUp className="mr-2 inline" size={16} />Nhập CSV / Excel / JSON</Link></div>}>
    {message && <div className={`mb-5 rounded-xl border px-4 py-3 text-sm ${message.kind === 'ok' ? 'border-teal-400/40 bg-teal-400/10 text-teal-100' : 'border-rose-400/40 bg-rose-400/10 text-rose-200'}`}>{message.text}</div>}
    <form className="panel mb-5 grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4" onSubmit={(event: FormEvent) => { event.preventDefault(); create.mutate(); }}><input className="input" required placeholder="Tên contact" value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} /><input className="input" placeholder="Zalo user_id" value={form.platformUserId} onChange={(event) => setForm({ ...form, platformUserId: event.target.value })} /><input className="input" placeholder="Số điện thoại (không dò tìm)" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /><input className="input" type="email" placeholder="Email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /><select className="input" value={form.consentStatus} onChange={(event) => setForm({ ...form, consentStatus: event.target.value as ContactForm['consentStatus'] })}><option>UNKNOWN</option><option>OPTED_IN</option><option>OPTED_OUT</option></select><input className="input" required placeholder="Nguồn dữ liệu" value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value })} /><input className="input" placeholder="Nguồn consent / legal basis" value={form.consentSource} onChange={(event) => setForm({ ...form, consentSource: event.target.value })} /><button className="button-primary" disabled={create.isPending}><UserPlus className="mr-2 inline" size={16} />Lưu contact</button></form>

    <div className="panel mb-5 p-4"><div className="grid gap-3 lg:grid-cols-[1fr_220px_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={16} /><input className="input !pl-9" placeholder="Tìm tên, SĐT, email, Zalo ID…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select className="input" value={consentFilter} onChange={(event) => setConsentFilter(event.target.value)}><option value="">Mọi trạng thái consent</option><option>OPTED_IN</option><option>UNKNOWN</option><option>OPTED_OUT</option></select><Link href="/segments" className="button-ghost text-center">Quản lý segment</Link></div>
      {selected.length > 0 && <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-[var(--border)] pt-4"><span className="mr-2 text-sm font-semibold">Đã chọn {selected.length}</span><select className="input !w-auto !py-2 text-xs" value={tagId} onChange={(event) => setTagId(event.target.value)}><option value="">Chọn tag</option>{tags.data?.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><button className="button-ghost !py-2 text-xs" disabled={!tagId || bulk.isPending} onClick={() => bulk.mutate('TAG')}><TagIcon className="mr-1 inline" size={14} />Gắn tag</button><button className="button-ghost !py-2 text-xs" disabled={bulk.isPending} onClick={() => bulk.mutate('OPT_IN')}><UserCheck className="mr-1 inline" size={14} />Opt-in</button><button className="button-ghost !py-2 text-xs" disabled={bulk.isPending} onClick={() => bulk.mutate('OPT_OUT')}><UserX className="mr-1 inline" size={14} />Opt-out</button><button className="button-ghost !py-2 text-xs" disabled={bulk.isPending} onClick={() => bulk.mutate('ARCHIVE')}><Archive className="mr-1 inline" size={14} />Lưu trữ</button></div>}
      <div className="mt-4 flex gap-2 border-t border-[var(--border)] pt-4"><input className="input !max-w-xs !py-2 text-sm" placeholder="Tạo tag mới" value={tagName} onChange={(event) => setTagName(event.target.value)} /><button className="button-ghost !py-2 text-sm" disabled={!tagName.trim() || createTag.isPending} onClick={() => createTag.mutate()}><TagIcon className="mr-1 inline" size={14} />Tạo tag</button></div>
    </div>

    {items.length ? <div className="panel overflow-x-auto"><table className="data-table"><thead><tr><th><input type="checkbox" checked={allSelected} onChange={(event) => setSelected(event.target.checked ? items.map((item) => item.id) : [])} aria-label="Chọn tất cả" /></th><th>Contact</th><th>Platform / user_id</th><th>Liên hệ</th><th>Tag</th><th>Nguồn</th><th>Consent</th></tr></thead><tbody>{items.map((contact) => <tr key={contact.id}><td><input type="checkbox" checked={selected.includes(contact.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, contact.id] : selected.filter((id) => id !== contact.id))} aria-label={`Chọn ${contact.displayName}`} /></td><td className="font-medium">{contact.displayName}</td><td>{contact.platform}<div className="text-xs text-[var(--muted)]">{contact.platformUserId ?? '—'}</div></td><td className="text-sm">{contact.normalizedPhone ?? contact.email ?? '—'}</td><td><div className="flex flex-wrap gap-1">{contact.tags.map(({ tag }) => <span className="rounded-full border px-2 py-1 text-[10px]" style={{ borderColor: tag.color, color: tag.color }} key={tag.id}>{tag.name}</span>)}</div></td><td className="text-sm text-[var(--muted)]">{contact.source ?? 'Manual'}</td><td><Status tone={contact.suppressed ? 'danger' : contact.consentStatus === 'OPTED_IN' ? 'success' : 'warning'}>{contact.suppressed ? 'SUPPRESSED' : contact.consentStatus}</Status></td></tr>)}</tbody></table></div> : <Empty title="Không có contact phù hợp" description="Nhập dữ liệu hợp pháp hoặc thay đổi bộ lọc. Hệ thống không dò số điện thoại hay scrape dữ liệu cá nhân." />}
  </AppShell>;
}
