'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { Empty, Status } from '@/components/ui';
import { api } from '@/lib/api';
import { useSession } from '@/lib/store';

interface ProxyRecord { id: string; name: string; type: string; host: string; port: number; status: string; latencyMs?: number; _count: { accounts: number } }
export default function ProxiesPage() { const workspaceId = useSession((state) => state.workspaceId); const client = useQueryClient(); const [form, setForm] = useState({ name: '', type: 'HTTPS', host: '', port: 443, username: '', password: '' }); const query = useQuery({ queryKey: ['proxies', workspaceId], queryFn: () => api<ProxyRecord[]>(`/workspaces/${workspaceId}/proxies`), enabled: Boolean(workspaceId) }); const create = useMutation({ mutationFn: () => api(`/workspaces/${workspaceId}/proxies`, { method: 'POST', body: JSON.stringify({ ...form, username: form.username || undefined, password: form.password || undefined }) }), onSuccess: async () => { setForm({ name: '', type: 'HTTPS', host: '', port: 443, username: '', password: '' }); await client.invalidateQueries({ queryKey: ['proxies', workspaceId] }); } }); return <AppShell title="Proxy management" subtitle="Credential được mã hóa AES-256-GCM; API không bao giờ trả username/password đã lưu."><form className="panel mb-5 grid gap-3 p-5 md:grid-cols-3" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><input className="input" required placeholder="Tên proxy" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><select className="input" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option>HTTP</option><option>HTTPS</option><option>SOCKS5</option></select><input className="input" required placeholder="Host" value={form.host} onChange={(event) => setForm({ ...form, host: event.target.value })} /><input className="input" required type="number" min="1" max="65535" value={form.port} onChange={(event) => setForm({ ...form, port: Number(event.target.value) })} /><input className="input" placeholder="Username (optional)" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><input className="input" type="password" placeholder="Password (optional)" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><button className="button-primary md:col-start-3">Lưu proxy</button></form>{query.data?.length ? <div className="panel overflow-x-auto"><table className="data-table"><thead><tr><th>Tên</th><th>Endpoint</th><th>Loại</th><th>Tài khoản</th><th>Trạng thái</th></tr></thead><tbody>{query.data.map((item) => <tr key={item.id}><td className="font-medium">{item.name}</td><td>{item.host}:{item.port}</td><td>{item.type}</td><td>{item._count.accounts}</td><td><Status tone={item.status === 'HEALTHY' ? 'success' : 'neutral'}>{item.status}</Status></td></tr>)}</tbody></table></div> : <Empty title="Chưa cấu hình proxy" description="Proxy là tùy chọn hạ tầng; không được dùng để né giới hạn hoặc chính sách nền tảng." />}</AppShell>; }
